# Generated by Django 3.1.5 on 2021-01-05 22:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recordstore', '0002_auto_20210105_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='content',
        ),
        migrations.AddField(
            model_name='record',
            name='artist',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='record',
            name='genre',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='record',
            name='name',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='record',
            name='year',
            field=models.IntegerField(default=1900, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2050)]),
        ),
    ]
